import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class TermsAndConditionsPage extends StatefulWidget {
  @override
  _TermsAndConditionsPageState createState() => _TermsAndConditionsPageState();
}

class _TermsAndConditionsPageState extends State<TermsAndConditionsPage> {
  bool _isChecked = false;

  void _onAgree() async {
    // Obtain shared preferences.
    final prefs = await SharedPreferences.getInstance();
    // Save that the intro has done
    await prefs.setBool('introDoneAndTermsAndConditionsAgreed', true);
    Navigator.of(context).pushNamedAndRemoveUntil(
        '/login-screen', (Route<dynamic> route) => false);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Terms and Conditions'),
      ),
      body: Padding(
        padding: EdgeInsets.all(16.0),
        child: ListView(
          children: <Widget>[
            Text(
              '''Terms of Use for Mobile App - Data Collection from AI Engine

Welcome to JournAi ("the App"). By using this App, you agree to comply with and be bound by the following Terms of Use. Please read these Terms carefully before using the App.

1. Data Collection and Accuracy:

a. The App utilizes an AI engine to provide certain features and functionalities. The data presented by the App is generated using AI algorithms and may not always be accurate or up-to-date.

b. We cannot guarantee the absolute accuracy, completeness, or reliability of the data provided by the AI engine. The App is provided on an "as is" and "as available" basis.

c. The data generated by the AI engine is subject to continuous improvement and refinement. As a result, there might be occasional discrepancies or errors in the information presented.

d. By using the App, you acknowledge and agree that any decisions made based on the data provided by the AI engine are solely at your own risk, and you should exercise caution and independent judgment.

2. User Responsibilities:

a. You are solely responsible for your use of the App and the information provided by the AI engine. You must use the App in accordance with all applicable laws and regulations.

b. Do not rely solely on the data provided by the AI engine for critical decision-making. Consider consulting with qualified professionals or experts when needed.

c. You must not attempt to reverse-engineer, modify, or misuse the App or its AI engine in any way that may violate intellectual property rights or applicable laws.

3. Privacy and Data Security:

a. We collect certain information from your use of the App, as described in our Privacy Policy. By using the App, you consent to the collection, use, and sharing of data as outlined in the Privacy Policy.

b. We take reasonable measures to safeguard the data and protect your privacy. However, given the nature of data transmission over the internet and AI systems, we cannot guarantee the security of information shared through the App.

4. Intellectual Property:

a. The App and its AI engine, including but not limited to its design, content, trademarks, and logos, are the property of JournAi group and its licensors. They are protected by copyright and other intellectual property laws.

b. You may not reproduce, modify, distribute, or create derivative works based on the App or its AI engine without our prior written consent.

5. Termination:

a. We reserve the right to suspend or terminate your access to the App at any time and for any reason, without prior notice.

b. Upon termination, all provisions of these Terms of Use that would reasonably be expected to survive termination, including but not limited to intellectual property provisions, disclaimer of warranties, and limitation of liability, shall continue to apply.

6. Limitation of Liability:

a. In no event shall JournAi group, its officers, directors, employees, or agents be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in connection with the use of the App or the data provided by the AI engine.

b. We shall not be responsible for any loss, damage, or injury resulting from errors, omissions, or inaccuracies in the data provided by the AI engine.

7. Changes to Terms of Use:

a. We reserve the right to modify these Terms of Use at any time, without prior notice. The updated Terms will be posted within the App, and your continued use of the App after the modifications signify your acceptance of the updated Terms.

By using the App, you acknowledge that you have read, understood, and agreed to these Terms of Use. If you do not agree with these Terms, you must refrain from using the App. If you have any questions or concerns about these Terms, please contact us at [Your Contact Email].''',
              style: TextStyle(fontSize: 16.0),
            ),
            SizedBox(height: 20.0),
            Row(
              children: <Widget>[
                Checkbox(
                  value: _isChecked,
                  onChanged: (value) {
                    setState(() {
                      _isChecked = value ?? false;
                    });
                  },
                ),
                GestureDetector(
                  onTap: () {
                    setState(() {
                      _isChecked = !_isChecked;
                    });
                  },
                  child: Text(
                    'I agree to the Terms and Conditions',
                    style: TextStyle(fontSize: 16.0),
                  ),
                ),
              ],
            ),
            SizedBox(height: 20.0),
            ElevatedButton(
              child: Text('Continue'),
              onPressed: _isChecked ? _onAgree : null,
            ),
          ],
        ),
      ),
    );
  }
}
